### ISSUE TITLE
Lua error on login

### ISSUE THREAD

**Issue by filliph** [BelegCufea/PrettyReputation#4]
```
4x PrettyReputation/core.lua:139: attempt to index field '?' (a nil value)
[string "@PrettyReputation/core.lua"]:139: in function `setupFactions'
[string "@PrettyReputation/core.lua"]:550: in function <PrettyReputation/core.lua:547>
[string "=[C]"]: ?
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:542: in function `UIParentLoadAddOn'
[string "@Rarity/Core/Collections.lua"]:63: in function `ScanToys'
[string "@Rarity/Core/Collections.lua"]:283: in function `ScanExistingItems'
[string "@Rarity/Core.lua"]:174: in function `DoEnable'
[string "@Rarity/Core.lua"]:150: in function <Rarity/Core.lua:149>
...
[string "@FrameXML/UIParent.lua"]:542: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:751: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>
```

The reputation bar also ignores the setting, which I suspect is related to this issue. I have to tick and un-tick the "Enabled" setting in "Reputation bars".

**Comment by BelegCufea** [comment]
Oops, sorry for missing this earlier. I don’t monitor this repository as it is just a guide for creating your own TAGS. I assume you are referring to [Pretty Reputation](https://github.com/BelegCufea/PrettyReputation) and not this project.

Anyway, I have a fix for the on-screen bars ready. I was planning to release it on the 10.0.7 patch day, but I can do it sooner :-)

Regarding the error you posted, it is quite strange. When did it start happening? Which version were you using? The code in that section has been the same since nearly the beginning. Maybe it has something to do with the language settings in the game. I have only tried English (because there is no option for my native language :-)).

I have uploaded my “fixes” to [Pretty Reputation](https://github.com/BelegCufea/PrettyReputation). I’m not sure if you know how to download the code from there (click on the big green button Code and then Download ZIP) and then install it (just extract it to ...\World of Warcraft\_retail_\Interface\addons\ directory). If you can and try it, that would be great.

Thanks for reporting the issue.

**Comment by filliph** [comment]
Ahh sorry for posting it in the wrong repo, I totally missed the URL 😅 

I was using the latest version from CurseForge, first time install as I've never used this add-on before. I'll grab the latest `master` and try it later tonight and re-post in the correct repo if there's still an issue 🙂

**Comment by BelegCufea** [comment]
Thank you. It will be very helpful. I made some minor adjustments to the code. Let’s hope it will resolve the issue.

I moved the issue to the correct repository :-) So no need for re-post.

Have a nice day.

**Comment by filliph** [comment]
The `master` branch fixed the Lua error, but it has not fixed the bar showing even though I've disabled it:

![image](https://user-images.githubusercontent.com/9424286/226437066-3f8f85e1-58b3-4652-b5ab-02bc923b5d4c.png)
![image](https://user-images.githubusercontent.com/9424286/226437256-48159053-36e6-4725-bb29-f48461009889.png)

**Comment by BelegCufea** [comment]
OK, thank you very much!
You are awesome.

That pesky BarsThatWontHide will I conquer :-)

Will post fixed version (with fixed hiding bars on login) soon on curse.
